.\" Hey, EMACS: -*- nroff -*-
.TH CC-QSYSDBUS-BOOT 1 "20 SEP 2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
cc-qsysdbus-boot \- launch system dbus server
.SH SYNOPSIS
.B cc-qsysdbus-boot
.SH DESCRIPTION
.B cc-qsysdbus-boot
It is used to launch system dbus server that realize by qt. Need to use root privilege.
.PP
.SH SEE ALSO
.BR cc-qsysdbus-boot (1),
.br
.SH AUTHOR
cc-qsysdbus-boot was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

