.\" Hey, EMACS: -*- nroff -*-
.TH CHANGEOTHERUSERPWD 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
changeotheruserpwd \- launch ukui-control-center program
.SH SYNOPSIS
.B changeotheruserpwd
.SH DESCRIPTION
.B changeotheruserpwd
It is used to launch program of changeotheruserpwd.
.PP
.SH SEE ALSO
.BR changeotheruserpwd (1),
.br
.SH AUTHOR
changeotheruserpwd was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

