.\" Hey, EMACS: -*- nroff -*-
.TH CHANGEUSERPWD 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
CHANGEUSERPWD \- launch ukui-control-center program
.SH SYNOPSIS
.B changeuserpwd
.SH DESCRIPTION
.B changeuserpwd
It is used to launch program of changeuserpwd.
.PP
.SH SEE ALSO
.BR changeuserpwd (1),
.br
.SH AUTHOR
changeuserpwd was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

