.\" Hey, EMACS: -*- nroff -*-
.TH CHECKUSERPWD 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
checkuserpwd \- launch ukui-control-center program
.SH SYNOPSIS
.B checkuserpwd
.SH DESCRIPTION
.B checkuserpwd
It is used to launch program of checkuserpwd.
.PP
.SH SEE ALSO
.BR checkuserpwd (1),
.br
.SH AUTHOR
checkuserpwd was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

