.\" Hey, EMACS: -*- nroff -*-
.TH CHILDCHECKPWDWITHPAM 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
childcheckpwdwithpam \- launch ukui-control-center program
.SH SYNOPSIS
.B childcheckpwdwithpam
.SH DESCRIPTION
.B childcheckpwdwithpam
It is used to launch program of childcheckpwdwithpam.
.PP
.SH SEE ALSO
.BR childcheckpwdwithpam (1),
.br
.SH AUTHOR
childcheckpwdwithpam was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

