.\" Hey, EMACS: -*- nroff -*-
.TH GROUP-MANAGER-SERVER 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
group-manager-server \- launch ukui-control-center program
.SH SYNOPSIS
.B group-manager-server
.SH DESCRIPTION
.B group-manager-server
It is used to launch program of group-manager-server.
.PP
.SH SEE ALSO
.BR group-manager-server (1),
.br
.SH AUTHOR
group-manager-server was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

