.\" Hey, EMACS: -*- nroff -*-
.TH LAUNCHSYSDBUS 1 "20 SEP 2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
launchSysDbus \- launch system dbus server
.SH SYNOPSIS
.B launchSysDbus
.SH DESCRIPTION
.B launchSysDbus
It is used to launch system dbus server that realize by qt. Need to use root privilege.
.PP
.SH SEE ALSO
.BR launchSysDbus (1),
.br
.SH AUTHOR
launchSysDbus was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

