.\" Copyright (C) 2014 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\" Copyright (C) 2016,Tianjin KYLIN Information Technology Co., Ltd.
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH ukui-typing-monitor 1 "2014\-05\-02" "UKUI"
.SH NAME
ukui-typing-monitor \- configure UKUI network proxy
.SH SYNOPSIS
.B ukui-typing-monitor
.RI [ OPTIONS... ]
.SH DESCRIPTION
This executable is part of the package 'ukui\-control\-center': The UKUI Control Center.
.PP
If you use too much computer you may be risking your health. Use this tool for
reminding yourself to take little (typing) breaks in regular intervals.
.PP
During the break, you can:
.PP
  o Stretch arms and legs

  o Open the window and breathe in

  o Juggle with balls or clubs

  o Close and rub your eyes

  o Have some fine green or herbal tea
.SH OPTIONS
This program accepts the standard UKUI and GTK options.
.SH AUTHORS
This manual page was writtenby Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
for the Debian project (but may be used by others).
.SH SEE ALSO
Latest version of the UKUI Desktop User Guide for your platform.
.PP
.BR "ukui-control-center" (1),
.BR "gtk-options" (7)
