.\" Hey, EMACS: -*- nroff -*-
.TH UKUI-CONTROL-CENTER-SESSION 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ukui-control-center-session \- launch ukui-control-center-session program
.SH SYNOPSIS
.B ukui-control-center-session
.SH DESCRIPTION
.B ukui-control-center-session
It is used to launch program of ukui-control-center-session.
.PP
.SH SEE ALSO
.BR ukui-control-center-session (1),
.br
.SH AUTHOR
ukui-control-center-session was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

