.\" Hey, EMACS: -*- nroff -*-
.TH UKUI-CONTROL-CENTER 1 "20 SEP  2019"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ukui-control-center \- launch ukui-control-center program
.SH SYNOPSIS
.B ukui-control-center
.SH DESCRIPTION
.B ukui-control-center
It is used to launch program of ukui-control-center.
.PP
.SH SEE ALSO
.BR ukui-control-center (1),
.br
.SH AUTHOR
ukui-control-center was written by hebing <hebing@kylinos.cn>.
.PP
This manual page was written by hebing <hebing@kylinos.cn>.

