/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c defender_interface -p defender_interface.h:defender_interface.cpp ../dbus_xml/KscDefender.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "defender_interface.h"

/*
 * Implementation of interface class defender_interface
 */

defender_interface::defender_interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

defender_interface::~defender_interface()
{
}

